FROM golang:alpine as builder
RUN mkdir /build 
ADD . /build/
WORKDIR /build
RUN go build -C gohost-api -o api .

FROM golang:alpine
COPY --from=builder /build/gohost-api/api /app/

ENTRYPOINT ["/app/api"]
